
security:
    #  Hachage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User: 'auto'

    #  Fournisseurs d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

  
    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

       
        public:
            pattern: ^/users/(login|register|login-form|register-form|settings|forgot-password|reset-password|change-password-form)
            stateless: true
            security: false

        # Routes messagerie avec JWT
        messages:
            pattern: ^/messages
            stateless: true
            provider: app_user_provider
            jwt: ~

        # Routes API JSON avec JWT
        api:
            pattern: ^/(users|projects|tasks|containers|notifications)/(?!login-form|register-form|settings|dashboard|index|show/|tasks$|page$)
            stateless: true
            provider: app_user_provider
            jwt: ~

        main:
            lazy: true
            provider: app_user_provider
         


    access_control:
      
        - { path: ^/users/login-form, roles: PUBLIC_ACCESS }
        - { path: ^/users/register-form, roles: PUBLIC_ACCESS }
        - { path: ^/users/login$, roles: PUBLIC_ACCESS }
        - { path: ^/users/register$, roles: PUBLIC_ACCESS }
        - { path: ^/users/settings, roles: PUBLIC_ACCESS } 

        - { path: ^/users/forgot-password, roles: PUBLIC_ACCESS }
        - { path: ^/users/reset-password, roles: PUBLIC_ACCESS }
        
        - { path: ^/users/change-password-form, roles: PUBLIC_ACCESS }  
        - { path: ^/users/change-password$, roles: IS_AUTHENTICATED_FULLY }  
       
        - { path: ^/notifications/page$, roles: PUBLIC_ACCESS }
        
     
        - { path: ^/users/dashboard, roles: PUBLIC_ACCESS }
        - { path: ^/projects/dashboard, roles: PUBLIC_ACCESS }
        - { path: ^/projects/index, roles: PUBLIC_ACCESS }
        - { path: ^/projects/show/\d+, roles: PUBLIC_ACCESS }
        - { path: ^/projects/\d+/tasks, roles: PUBLIC_ACCESS }
     
        - { path: ^/messages, roles: IS_AUTHENTICATED_FULLY }
    
        - { path: ^/users/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/projects/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/tasks/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/containers/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/notifications/, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4       
                time_cost: 3  
                memory_cost: 10