
controllers:
    resource: routing.controllers


well_known_ignore:
    path: /.well-known/{path}
    controller: Symfony\Component\HttpKernel\Controller\ErrorController::preview
    requirements:
        path: ".+"
    defaults:
        code: 404


system_files:
    path: /{file}
    controller: Symfony\Component\HttpKernel\Controller\ErrorController::preview
    requirements:
        file: "(favicon\\.ico|robots\\.txt|sitemap\\.xml|apple-touch-icon.*\\.png)"
    defaults:
        code: 404